# Generated by Django 3.1.4 on 2021-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_award_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='points',
            field=models.IntegerField(choices=[(100, 'Bsa'), (20, 'Bqa'), (80, 'Bpa'), (70, 'Bda')]),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(choices=[('BSA', 'Best Student Award'), ('BQA', 'Best Question Award'), ('BPA', 'Best Presentation Award'), ('BDA', 'Best Design Award')], max_length=200),
        ),
    ]
