# Generated by Django 3.1.4 on 2021-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210228_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='points',
            field=models.IntegerField(choices=[(100, 'Bsa 100'), (20, 'Bqa 20'), (80, 'Bpa 80'), (70, 'Bda 70')]),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(choices=[('Best Student Award', 'BSA'), ('Best Question Award', 'BQA'), ('Best Presentation Award', 'BPA'), ('Best Design Award', 'BDA')], max_length=200),
        ),
    ]
